// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVKSJWT8MGhwiRB1z2GVSDFpssO68WFdU',
    appId: '1:661814595411:web:3eec85a87600d90f41dba6',
    messagingSenderId: '661814595411',
    projectId: 'sportsyncpro',
    authDomain: 'sportsyncpro.firebaseapp.com',
    storageBucket: 'sportsyncpro.appspot.com',
    measurementId: 'G-RNJQK0W85Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKnHvY3U3uKYd0Lask7DEXpznBdCPS15I',
    appId: '1:661814595411:android:1a9487a612d3afa841dba6',
    messagingSenderId: '661814595411',
    projectId: 'sportsyncpro',
    storageBucket: 'sportsyncpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu603d3EYGnagYWNqNUhtLS__2Wr2Dw6k',
    appId: '1:661814595411:ios:d4d77421edc71ba341dba6',
    messagingSenderId: '661814595411',
    projectId: 'sportsyncpro',
    storageBucket: 'sportsyncpro.appspot.com',
    iosBundleId: 'com.example.sportSyncPro',
  );
}
